### ISSUE TITLE
Download Through Title or other Input Source?

### ISSUE THREAD

**Issue by abhi0618** [Tishacy/SciDownl#23]
Hi, I've been trying the tool in multiple ways now, and have been finding it quite interesting. I was curious to know if its possible to crawl papers based on their titles , because there are some older papers(older than the year 2000) ,which do not have an associated dois linked with them on scopus.But they are highly cited papers of those journals , and said papers can be found on Scihub through the title search. Was wondering if similiar thing can be achieved through the CLI tool

**Comment by Tishacy** [comment]
Downloading papers based on titles has been supported in the new version v1.0.2. You can have a try with this:
```bash
# Update to the newest version
$ pip3 install -U scidownl

# Download a paper with its title
$ scidownl download --title "ImageNet Classification with Deep Convolutional Neural Networks"
```
Hope it will help you 😃 

> Hi, I've been trying the tool in multiple ways now, and have been finding it quite interesting. I was curious to know if its possible to crawl papers based on their titles , because there are some older papers(older than the year 2000) ,which do not have an associated dois linked with them on scopus.But they are highly cited papers of those journals , and said papers can be found on Scihub through the title search. Was wondering if similiar thing can be achieved through the CLI tool
