### ISSUE TITLE
new url

### ISSUE THREAD

**Issue by lvvn** [Tishacy/SciDownl#5]
你好，大部分scihub的ulr都不能用了，能否加上可用的https://libgen.wikicn.top/
或者可以直接选择http://gen.lib.rus.ec/scimag/
多谢

**Comment by Tishacy** [comment]
有一些实时更新可用 sci-hub 的网站呀，比如：http://tool.yovisun.com/scihub/ 和 https://lovescihub.wordpress.com/。

scidownl里有两种方式可以更新可用的sci-hub网址
- `scidownl -u`：通过 http://tool.yovisun.com/scihub/ 获取可用的 sci-hub 网址
- `scidownl -b`：通过暴力筛选，选出可用的 sci-hub 网址（连接时长不超过3000ms）

一般这两种方式的结果会有一些出入，但是最后应该都是可用的 sci-hub 网址。

最后，因为这个模块是针对 sci-hub 做的一个非官方api，暂时不考虑将其他文献源网站加进来~ 希望理解

**Comment by lvvn** [comment]
多谢回复
On 7/30/2020 23:45，Tishacy<notifications@github.com> wrote：

有一些实时更新可用 sci-hub 的网站呀，比如：http://tool.yovisun.com/scihub/ 和 https://lovescihub.wordpress.com/。

scidownl里有两种方式可以更新可用的sci-hub网址

scidownl -u：通过 http://tool.yovisun.com/scihub/ 获取可用的 sci-hub 网址
scidownl -b：通过暴力筛选，选出可用的 sci-hub 网址（连接时长不超过3000ms）

一般这两种方式的结果会有一些出入，但是最后应该都是可用的 sci-hub 网址。

最后，因为这个模块是针对 sci-hub 做的一个非官方api，暂时不考虑将其他文献源网站加进来~ 希望理解
